// <auto-generated />
using System;
using CryptoAgent.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CryptoAgentDbContext))]
    [Migration("20251211121437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CryptoAgent.Api.Data.MarketSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtcChange24hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BtcChange7dPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BtcPriceGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthChange24hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthChange7dPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthPriceGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshots", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.PerformanceSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CumulatedAiCostGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulatedFeesGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetDepositsGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PortfolioValueGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VaultGbp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerformanceSnapshots", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.PortfolioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtcAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighWatermarkGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VaultGbp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.TradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeeGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PAPER");

                    b.Property<decimal>("PriceGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
