// <auto-generated />
using System;
using CryptoAgent.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CryptoAgentDbContext))]
    partial class CryptoAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CryptoAgent.Api.Backtesting.Entities.BacktestMetricEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AvgTradePnlGbp")
                        .HasColumnType("TEXT");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Baseline_Dca_FinalValueGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Baseline_Hodl_FinalValueGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Baseline_Rebalance_FinalValueGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeesPaidGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalValueGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdownPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfitGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfitPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SharpeLike")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SlippagePaidGbp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WinRatePct")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId")
                        .IsUnique();

                    b.ToTable("BacktestMetrics", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Backtesting.Entities.BacktestRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DecisionCadenceHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("EndHourUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeePct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialCashGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxBtcAllocationPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxEthAllocationPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxTradeSizeGbp")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTradesPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinCashAllocationPct")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PAPER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectorMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Deterministic");

                    b.Property<decimal>("SlippagePct")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartHourUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarmupHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(168);

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Backtesting.Entities.BacktestStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtcAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BtcCloseGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("BtcRegime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthCloseGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("EthRegime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValueGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VaultGbp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId", "HourUtc")
                        .IsUnique();

                    b.ToTable("BacktestSteps", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Backtesting.Entities.BacktestTradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FeeGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SlippageGbp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.ToTable("BacktestTrades", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.DecisionLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtcCostBasisGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BtcUnrealisedPnlGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BtcValueGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("EthCostBasisGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("EthUnrealisedPnlGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("EthValueGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExogenousSummary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ExogenousTraceJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("FinalAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalAsset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalSizeGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmAsset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LlmConfidence")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LlmSizeGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RationaleDetailed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RationaleShort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawModelOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValueGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("DecisionLogs", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.DecisionInputsExogenousEntity", b =>
                {
                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AbstainModifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlignmentFlagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceThresholdModifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatingReasonJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("MarketAlignmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionSizeModifier")
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1m);

                    b.Property<string>("ThemeScoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeConflictJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("ThemeDirectionJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("ThemeStrengthJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("TraceIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TimestampUtc");

                    b.HasIndex("TimestampUtc")
                        .IsUnique();

                    b.ToTable("DecisionInputsExogenous", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.ExogenousClassificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectionalBias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactHorizon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyEntitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NoveltyScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryBulletsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeRelevance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ItemId");

                    b.HasIndex("ThemeRelevance");

                    b.ToTable("ExogenousClassifications", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.ExogenousItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawExcerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SourceCredibilityWeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ExogenousItems", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.HourlyCandleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CloseGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LowGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpenGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("CoinGecko");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asset", "HourUtc")
                        .IsUnique();

                    b.ToTable("HourlyCandles", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.HourlyFeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Drawdown7d")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MomentumScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Return1h")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Return24h")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Return7d")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sma168")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sma24")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TrendStrength")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vol24h")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vol72h")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asset", "HourUtc")
                        .IsUnique();

                    b.ToTable("HourlyFeatures", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.NarrativeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectionalBias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StateScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("Theme");

                    b.ToTable("Narratives", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.NarrativeItemEntity", b =>
                {
                    b.Property<Guid>("NarrativeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContributionWeight")
                        .HasColumnType("TEXT");

                    b.HasKey("NarrativeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("NarrativeId");

                    b.ToTable("NarrativeItems", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.RegimeStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asset", "HourUtc")
                        .IsUnique();

                    b.ToTable("RegimeStates", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.Entities.StrategySignalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SignalScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuggestedSizeGbp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Asset", "HourUtc");

                    b.HasIndex("StrategyName", "HourUtc");

                    b.ToTable("StrategySignals", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.MarketSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtcChange24hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BtcChange7dPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BtcPriceGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthChange24hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthChange7dPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthPriceGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshots", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.PerformanceSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CumulatedAiCostGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulatedFeesGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetDepositsGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PortfolioValueGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VaultGbp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerformanceSnapshots", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.PortfolioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtcAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BtcCostBasisGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CashGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EthCostBasisGbp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("HighWatermarkGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VaultGbp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("CryptoAgent.Api.Data.TradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AssetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("FeeGbp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PAPER");

                    b.Property<decimal>("PriceGbp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeGbp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
